# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broadcastingstatus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timerange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'Khung giờ phát sóng'), (2, 'mất sóng do sự cố máy phát'), (3, 'mất sóng máy phát do nguyên nhân khác'), (4, 'mất sóng tín hiệu')], default=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('broadcasting_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broadcastingstatus.Broadcastingstatus')),
            ],
            options={
                'db_table': 'time_ranges',
            },
        ),
    ]
