# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Tây Bắc', 'Tây Bắc'), ('Đông Bắc', 'Đông Bắc'), ('Đồng Bằng Sông Hồng', 'Đồng Bằng Sông Hồng'), ('Bấc Trung Bộ', 'Bấc Trung Bộ'), ('Nam Trung Bộ', 'Nam Trung Bộ'), ('Tây Nguyên', 'Tây Nguyên'), ('Đông Nam Bộ', 'Đông Nam Bộ'), ('Đồng Bằng Sông Cửu Long', 'Đồng Bằng Sông Cửu Long')], max_length=50)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
    ]
