# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 14:45
from __future__ import unicode_literals

from django.db import migrations
from areas.models import Area

AREAS = [
    {'name': 'Tây Bắc'},
    {'name': 'Đông Bắc'},
    {'name': 'Đồng Bằng Sông Hồng'},
    {'name': 'Bắc Trung Bộ'},
    {'name': 'Nam Trung Bộ'},
    {'name': 'Tây Nguyên'},
    {'name': 'Đông Nam Bộ'},
    {'name': 'Đồng Bằng Sông Cửu Long'},
]

def load_areas(apps, schema_editor):
    for area in AREAS:
        new_area = Area(name=area['name'])
        new_area.save()

def delete_areas(apps, schema_editor):
    Area.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_areas, delete_areas),
    ]
