# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20170919_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(choices=[('Tây Bắc', 'Tây Bắc'), ('Đông Bắc', 'Đông Bắc'), ('Đồng Bằng Sông Hồng', 'Đồng Bằng Sông Hồng'), ('Bắc Trung Bộ', 'Bắc Trung Bộ'), ('Nam Trung Bộ', 'Nam Trung Bộ'), ('Tây Nguyên', 'Tây Nguyên'), ('Đông Nam Bộ', 'Đông Nam Bộ'), ('Đồng Bằng Sông Cửu Long', 'Đồng Bằng Sông Cửu Long')], max_length=50),
        ),
    ]
